In [1]:
#Advanced machine learning -- Project 1
#Group -- Itworkslocally
#Zhengxu Li

In [2]:
import pandas as pd
import numpy as np
import os 
from sklearn.metrics import r2_score

In [3]:
sample_data = pd.read_csv("sample.csv")
X_test = pd.read_csv("X_test.csv")
X_train = pd.read_csv("X_train.csv")
y_train = pd.read_csv("y_train.csv")

In [4]:
X_train

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.0,14168.823171,10514.380717,3316.149698,94230.695124,102.386606,92.677127,11108.748199,10866.505510,10837.622093,...,NaN,12352.094085,846.014651,105.132144,102.112809,2090.004260,2.691845,1234.374109,1000.784475,9285.751272
1,1.0,17757.037554,NaN,4101.016273,92959.527633,NaN,99.855168,10013.959449,10826.607494,10076.101597,...,NaN,16198.071494,776.084467,106.385590,103.472030,2474.051881,2.287976,NaN,1012.626705,11750.284764
2,2.0,14226.656663,11029.642499,NaN,124055.600561,100.542483,92.860892,NaN,10492.342868,NaN,...,10329.704431,13976.063780,737.040332,103.671234,109.458246,2656.083281,2.843706,888.353607,1048.810385,9553.922728
3,3.0,8766.012436,7384.202998,2147.308418,100157.719990,104.855061,101.929026,10050.049932,10499.521099,10525.030989,...,10008.251395,6212.127347,329.044233,105.084488,104.858546,1097.785204,2.732257,927.752967,1048.357330,NaN
4,4.0,13801.016418,13269.493652,3408.316953,92048.527786,103.759758,95.789235,9667.353978,10750.783106,10618.800750,...,10095.782015,13772.061493,NaN,NaN,100.369834,2693.053231,2.702908,1471.354073,1071.284484,9423.533063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1207.0,18707.457475,13610.725702,3785.886941,113497.632841,109.526764,97.812339,11274.011935,10803.953566,10949.811419,...,8472.132451,17727.003274,1033.057071,104.838553,102.235191,3099.069091,3.079234,1362.889974,NaN,10110.360570
1208,1208.0,17108.239122,12168.536128,3442.619145,98218.773311,100.468476,109.994258,11031.326117,10231.743317,10687.321177,...,8839.251924,14721.087037,792.061138,105.823015,109.915094,3124.059793,2.935047,1577.404870,1026.749434,10620.330033
1209,1209.0,14264.707321,9273.405761,3580.894003,101668.927699,102.620705,104.470375,9159.594864,10661.827392,10623.176915,...,10264.321725,15226.056342,831.025190,101.926717,101.669153,2252.031870,NaN,1781.799720,1066.379647,10317.757445
1210,1210.0,14907.077440,10936.636575,3159.167789,100400.608972,106.622507,84.859872,10356.404262,10107.960852,10384.924460,...,10310.165709,12976.062457,852.001070,103.098317,104.397562,2585.048660,2.731768,1300.379678,1049.370040,10876.010268
1211,1211.0,14975.969273,11451.350347,3107.470343,100080.295868,108.040548,NaN,10766.888640,10726.567333,10632.289329,...,8853.948288,12953.077245,919.051273,107.668141,102.999153,2489.012323,2.721068,1416.819713,1088.315592,10359.138969

In [5]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (1212, 833)
y_train shape: (1212, 2)
X_test shape: (776, 833)

In [6]:
X_test

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.0,14655.540585,9917.388635,3368.691863,104367.124458,104.132894,95.412138,9222.286185,NaN,10054.751221,...,9153.072463,12039.009308,714.005017,105.651509,103.574436,2628.082823,2.766271,1553.285942,1037.998392,9762.400011
1,1.0,13875.822363,9955.163751,3118.195658,103577.269601,103.290975,86.916779,9625.725002,10592.011548,10234.818476,...,9915.292110,12579.041315,695.070183,106.900274,105.241730,2388.096545,NaN,1386.519117,1088.519466,11748.788738
2,2.0,14807.162495,10682.476988,3335.687716,106647.642610,109.481676,86.476353,9128.693785,10880.979240,10485.268796,...,9733.845509,11009.075093,663.093857,105.541065,101.875603,2097.004365,2.362592,1204.527342,1067.697534,12487.217965
3,3.0,12253.667985,9001.609788,2631.482012,91105.570966,108.741037,84.542046,9765.458299,10953.438053,10190.986014,...,11204.016625,9395.016940,656.018142,104.816602,107.213434,2035.045976,3.052844,794.341243,NaN,7931.828963
4,4.0,18925.988003,12161.366373,3724.006508,110262.565336,102.085795,107.920270,9494.243179,10684.550944,10074.187696,...,11093.701929,13876.039832,964.037692,104.557952,109.185247,2971.082813,2.571392,1207.265749,1013.661254,8241.962297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,771.0,12915.908280,10313.516386,3339.024965,NaN,109.580429,101.020255,10481.166660,10032.785913,10319.731898,...,9509.882736,11579.025189,689.031306,105.024718,104.720490,1783.051318,2.312930,1582.022774,1013.001968,NaN
772,772.0,14866.856670,8940.451109,3252.927684,113514.393499,101.136893,77.681767,9792.678721,10396.746372,10431.947890,...,9661.110937,12576.035460,684.081342,NaN,105.099666,2073.098397,NaN,1442.542973,NaN,9190.490042
773,773.0,16027.098672,NaN,3235.812109,115373.852361,106.789855,87.083643,10356.795371,10422.221126,10252.846021,...,10250.308929,14438.049119,882.011329,103.824762,101.585975,2913.049944,2.756702,1577.603214,1005.415175,NaN
774,774.0,NaN,10456.020618,3296.498787,96391.002522,NaN,88.246838,10260.564729,10330.240473,NaN,...,10681.223261,10523.011987,NaN,104.101975,103.134280,2077.039389,3.015341,1335.688605,1089.872409,10014.416818
775,775.0,16658.201515,10445.135943,4286.832195,111582.925768,105.649646,108.459925,NaN,10224.330962,10027.897616,...,8007.158246,NaN,949.078959,106.709434,102.258484,2910.022523,3.094579,2004.048055,1074.231739,11385.187349

## Subtask 0 Filling missing values  
Imputation of missing values  
We can imputate with mean value, median value or via KNN algorithm

In [7]:
#impute null values with median, in X_train and X_test
for i in X_train:
    X_train.loc[X_train.loc[:,i].isnull(),i]=X_train.loc[:,i].median()
for i in X_test:
    X_test.loc[X_test.loc[:,i].isnull(),i]=X_test.loc[:,i].median()

In [8]:
#There is no null value anymore
X_train.isna().sum().sum()

0

## Subtask 1 Outlier Detection  
IsolationForest(isolate anomalies in few number and different in feature space) from sklearn.ensemble import IsolationForest, 


Minimum Covariance Determinant(when inputs has Gaussian distribution) from sklearn import EllipticEnvelope, 


ABOD: Angle Based Outlier Detection  
This algorithm finds potential outliers by considering the variances of the angles between the data points. It still takes distances into account, but only as a secondary measure to normalize the results.

In [9]:
from pyod.models.abod import ABOD

In [10]:
OutlierDetector = ABOD()
OutlierDetector.fit(X_train)
#remember to change parameters

ABOD(contamination=0.1, method='fast', n_neighbors=5)

In [11]:
OutlierDetector.labels_.sum()#there are 122 outliers

122

In [12]:
X_train = X_train.loc[OutlierDetector.labels_ == 0]

In [13]:
X_train

,id,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.0,14168.823171,10514.380717,3316.149698,94230.695124,102.386606,92.677127,11108.748199,10866.505510,10837.622093,...,10064.750764,12352.094085,846.014651,105.132144,102.112809,2090.004260,2.691845,1234.374109,1000.784475,9285.751272
2,2.0,14226.656663,11029.642499,3401.539562,124055.600561,100.542483,92.860892,9991.006638,10492.342868,10494.225267,...,10329.704431,13976.063780,737.040332,103.671234,109.458246,2656.083281,2.843706,888.353607,1048.810385,9553.922728
4,4.0,13801.016418,13269.493652,3408.316953,92048.527786,103.759758,95.789235,9667.353978,10750.783106,10618.800750,...,10095.782015,13772.061493,792.045039,104.969600,100.369834,2693.053231,2.702908,1471.354073,1071.284484,9423.533063
5,5.0,11333.665744,9693.979681,2930.260890,98892.445927,103.967694,96.535053,10143.722727,10889.102260,10410.706045,...,9231.179277,12725.008650,669.093896,105.253377,102.903567,1959.062427,3.133662,1379.650990,1078.401787,8246.128523
6,6.0,18012.994905,13437.218514,3928.789039,105320.679828,109.316437,102.421881,10218.403724,10790.859751,10252.296757,...,9808.721441,14441.085548,1113.097352,104.969600,107.296259,3431.070928,2.778419,1783.483311,1015.515229,10780.194713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1207.0,18707.457475,13610.725702,3785.886941,113497.632841,109.526764,97.812339,11274.011935,10803.953566,10949.811419,...,8472.132451,17727.003274,1033.057071,104.838553,102.235191,3099.069091,3.079234,1362.889974,1053.778881,10110.360570
1208,1208.0,17108.239122,12168.536128,3442.619145,98218.773311,100.468476,109.994258,11031.326117,10231.743317,10687.321177,...,8839.251924,14721.087037,792.061138,105.823015,109.915094,3124.059793,2.935047,1577.404870,1026.749434,10620.330033
1209,1209.0,14264.707321,9273.405761,3580.894003,101668.927699,102.620705,104.470375,9159.594864,10661.827392,10623.176915,...,10264.321725,15226.056342,831.025190,101.926717,101.669153,2252.031870,2.710103,1781.799720,1066.379647,10317.757445
1210,1210.0,14907.077440,10936.636575,3159.167789,100400.608972,106.622507,84.859872,10356.404262,10107.960852,10384.924460,...,10310.165709,12976.062457,852.001070,103.098317,104.397562,2585.048660,2.731768,1300.379678,1049.370040,10876.010268
1211,1211.0,14975.969273,11451.350347,3107.470343,100080.295868,108.040548,99.670635,10766.888640,10726.567333,10632.289329,...,8853.948288,12953.077245,919.051273,107.668141,102.999153,2489.012323,2.721068,1416.819713,1088.315592,10359.138969

In [14]:
y_train

          id     y
0        0.0  74.0
1        1.0  51.0
2        2.0  70.0
3        3.0  52.0
4        4.0  85.0
...      ...   ...
1207  1207.0  70.0
1208  1208.0  86.0
1209  1209.0  68.0
1210  1210.0  71.0
1211  1211.0  53.0

[1212 rows x 2 columns]

In [15]:
y_train = y_train.loc[OutlierDetector.labels_ == 0]

In [16]:
y_train

          id     y
0        0.0  74.0
2        2.0  70.0
4        4.0  85.0
5        5.0  59.0
6        6.0  82.0
...      ...   ...
1207  1207.0  70.0
1208  1208.0  86.0
1209  1209.0  68.0
1210  1210.0  71.0
1211  1211.0  53.0

[1090 rows x 2 columns]

Drop the ID as we don not need them as features for prediction

In [17]:
X_train = X_train.drop('id', axis=1)

In [18]:
X_test = X_test.drop('id', axis=1)

In [19]:
y_train = y_train.drop("id", axis=1)

In [20]:
print("X_train,X_test,y_train:",X_train.shape,X_test.shape,y_train.shape)

X_train,X_test,y_train: (1090, 832) (776, 832) (1090, 1)

### Data normalization  
https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#results  
Probably when should normalize data here  
Removal of outliers creates a normal distribution in some of my variables, and makes transformations for the other variables more effective. Therefore, it seems that removal of outliers before transformation is the better option.  
Then select the relevant features and compare their importance.

Feature scaling  Normalization VS Standarization
Normalization is useful when we don’t know about the distribution	  
Standarization is useful when the feature distribution is Normal or Gaussian.

In [21]:
from sklearn import preprocessing
from sklearn.preprocessing import RobustScaler
scaler = preprocessing.RobustScaler().fit(X_train)
scaler

RobustScaler()

In [22]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[-0.37973274, -0.19294867, -0.19082417, ..., -0.4185679 ,
        -1.10360678, -0.55704844],
       [-0.35476666,  0.11285986,  0.        , ..., -1.55028303,
        -0.10346877, -0.34224881],
       [-0.53851083,  1.44221441,  0.01514571, ...,  0.3565128 ,
         0.36455363, -0.44668815],
       ...,
       [-0.33834061, -0.9294689 ,  0.40081061, ...,  1.3718747 ,
         0.26241056,  0.26956655],
       [-0.06103657,  0.05766073, -0.54163798, ..., -0.20268618,
        -0.09181395,  0.71671519],
       [-0.03129673,  0.36314402, -0.65716834, ...,  0.17814949,
         0.71922589,  0.30271227]])

In [23]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.16962224, -0.54726424, -0.07340608, ...,  0.62448401,
        -0.32862815, -0.17526294],
       [-0.50621793, -0.52484466, -0.63320005, ...,  0.07904657,
         0.72347156,  1.41579218],
       [-0.10416874, -0.09318331, -0.14716178, ..., -0.5161865 ,
         0.28985551,  2.00725828],
       ...,
       [ 0.42246415, -0.07235067, -0.37035782, ...,  0.70401752,
        -1.0071726 ,  0.02295375],
       [ 0.05728035, -0.22758546, -0.23473886, ..., -0.08720271,
         0.75164656,  0.02659716],
       [ 0.69490424, -0.23404553,  1.97839916, ...,  2.09877325,
         0.42593012,  1.1245552 ]])

In [24]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns = X_test.columns)

## Subtask 2 Feature Selection   
https://towardsdatascience.com/5-feature-selection-method-from-scikit-learn-you-should-know-ed4d116e4172    
SelectKBest  
The premise with SelectKBest is combining the univariate statistical test with selecting the K-number of features based on the statistical result between the X and y.

In [25]:
#SelectKBest
from sklearn.feature_selection import SelectKBest, mutual_info_regression
#Select top 80 features based on mutual info regression
selector = SelectKBest(mutual_info_regression, k = 80)
selector.fit(X_train_scaled, y_train)
X_train_scaled.columns[selector.get_support()]

C:\Users\zheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Index(['x23', 'x29', 'x69', 'x86', 'x87', 'x95', 'x115', 'x133', 'x146',
       'x159', 'x172', 'x194', 'x200', 'x203', 'x209', 'x214', 'x228', 'x231',
       'x233', 'x242', 'x243', 'x254', 'x278', 'x283', 'x286', 'x287', 'x298',
       'x306', 'x309', 'x310', 'x319', 'x320', 'x327', 'x334', 'x342', 'x349',
       'x362', 'x372', 'x380', 'x399', 'x402', 'x410', 'x415', 'x440', 'x445',
       'x458', 'x465', 'x479', 'x484', 'x485', 'x507', 'x511', 'x512', 'x531',
       'x538', 'x542', 'x543', 'x546', 'x571', 'x579', 'x589', 'x612', 'x640',
       'x641', 'x654', 'x672', 'x675', 'x702', 'x711', 'x712', 'x726', 'x742',
       'x745', 'x748', 'x766', 'x769', 'x777', 'x790', 'x799', 'x817'],
      dtype='object')

In [26]:
selected_features = X_train_scaled.columns[selector.get_support()].tolist()

In [27]:
selected_features

['x23',
 'x29',
 'x69',
 'x86',
 'x87',
 'x95',
 'x115',
 'x133',
 'x146',
 'x159',
 'x172',
 'x194',
 'x200',
 'x203',
 'x209',
 'x214',
 'x228',
 'x231',
 'x233',
 'x242',
 'x243',
 'x254',
 'x278',
 'x283',
 'x286',
 'x287',
 'x298',
 'x306',
 'x309',
 'x310',
 'x319',
 'x320',
 'x327',
 'x334',
 'x342',
 'x349',
 'x362',
 'x372',
 'x380',
 'x399',
 'x402',
 'x410',
 'x415',
 'x440',
 'x445',
 'x458',
 'x465',
 'x479',
 'x484',
 'x485',
 'x507',
 'x511',
 'x512',
 'x531',
 'x538',
 'x542',
 'x543',
 'x546',
 'x571',
 'x579',
 'x589',
 'x612',
 'x640',
 'x641',
 'x654',
 'x672',
 'x675',
 'x702',
 'x711',
 'x712',
 'x726',
 'x742',
 'x745',
 'x748',
 'x766',
 'x769',
 'x777',
 'x790',
 'x799',
 'x817']

In [28]:
X_train = X_train_scaled[selected_features]
X_train

,x23,x29,x69,x86,x87,x95,x115,x133,x146,x159,...,x726,x742,x745,x748,x766,x769,x777,x790,x799,x817
0,0.519100,-0.601275,-0.491437,1.143583,0.433522,0.819502,3.263182,-0.306290,1.027370,1.361892,...,-0.138977,-0.217168,0.068520,1.021614,0.186099,0.250819,0.232024,0.462036,-0.378288,0.744877
1,-0.060941,0.229769,-0.358702,0.749314,0.298169,0.574768,-0.289714,0.000000,0.108959,-0.071773,...,-1.063168,-0.881308,-0.075501,-0.071270,0.315368,0.255746,0.059350,0.527076,0.000000,0.204801
2,-0.327759,2.086763,0.128913,-0.298104,-0.102326,-0.478897,1.132566,0.187017,-0.013830,0.000000,...,1.093056,0.232347,-0.042304,-0.330089,-0.162287,-0.599480,-0.494193,0.000000,-0.644842,-0.562385
3,1.086303,-0.180478,-0.651683,0.174243,-0.214193,-0.350344,-0.751229,-0.152258,0.588155,0.000000,...,-1.296684,-0.518016,1.732685,1.584317,0.522580,1.495920,0.646352,1.339037,0.149242,1.689853
4,0.187793,-0.884384,1.209699,0.934095,0.000000,0.464781,6.945758,-2.040322,-0.229398,1.873588,...,1.649144,0.659238,0.413239,0.317118,0.332526,0.000000,-0.204497,-1.402851,-0.808644,-0.738082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,0.905130,1.203730,1.964570,-0.127725,0.486067,0.772018,-0.347216,0.594844,0.278330,-0.381707,...,0.455479,0.000000,0.000000,0.534842,0.393397,-0.237237,0.592379,-1.444880,-0.127986,-0.390427
1086,-0.842797,0.920760,0.844623,0.107370,0.757390,0.000000,0.369582,-0.229482,-0.898763,0.000000,...,1.513073,0.606277,-0.398704,0.020588,-0.808031,0.112378,-0.324612,-0.915371,-0.606101,-0.858305
1087,0.763059,-0.305248,0.297134,0.259987,-0.067702,0.609307,-0.200829,0.322867,0.635992,-0.370690,...,0.206339,16.772531,1.260594,0.368394,1.567864,0.420256,0.000000,0.274484,-0.980113,0.251683
1088,-0.118540,0.572516,-0.035154,0.174619,-0.171495,-0.424044,0.557481,-1.230293,0.468414,3.484066,...,-0.386994,-1.096365,0.114262,0.000000,0.850820,0.231930,0.367914,0.480972,0.676552,0.610156
1089,-0.025130,-0.203849,-0.175684,-1.109820,-0.868695,0.409115,0.000000,-0.074937,0.000000,-0.650986,...,-0.392335,-0.270418,0.000000,-0.202058,0.618447,0.152035,-0.272622,0.234016,1.057797,0.048024

In [29]:
X_test = X_test_scaled[selected_features]
X_test

,x23,x29,x69,x86,x87,x95,x115,x133,x146,x159,...,x726,x742,x745,x748,x766,x769,x777,x790,x799,x817
0,-0.103823,-0.403929,0.219117,0.069424,0.474960,-0.360481,-0.639616,0.451027,0.702619,-0.500387,...,0.978611,0.488257,0.191237,0.794534,-0.082287,-0.006295,0.279679,-0.050376,-0.622754,0.034539
1,-0.270397,-0.162507,-0.511469,-0.115053,-0.890939,0.917642,0.683268,-0.523815,0.126679,0.662570,...,0.502588,-0.153420,0.677790,0.093918,0.803846,0.183456,-0.095141,0.430021,-1.009032,-1.027171
2,-0.649416,0.557091,-0.748050,-0.689354,-1.397734,-0.663714,-0.235440,-0.303673,-1.331173,-0.027102,...,-1.160931,-0.883197,-0.107484,-0.787516,-0.495965,0.036195,-0.084979,0.505058,0.129073,-0.649133
3,-0.606841,-0.201326,-1.531841,-0.847173,-1.453360,-0.403430,-0.428336,-0.814717,0.111767,-0.403471,...,0.032609,-1.388309,-0.372581,-0.141746,-0.276675,-0.650933,0.204130,1.563245,-0.075585,-0.445636
4,-0.402426,-0.172730,0.892436,0.416422,0.674616,0.713908,-0.065017,0.145876,-0.019704,1.303920,...,0.145539,0.089070,-0.831328,0.307465,-0.108746,-0.619408,-0.277582,-1.457637,-0.619094,-0.484881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,-0.322166,-0.767432,-0.964999,-1.114779,-0.522580,0.040231,-0.549882,-0.217117,0.480326,-0.699248,...,0.100209,-0.010938,0.142264,-0.815225,-0.240307,-0.792653,0.221596,0.640609,-0.898740,-1.898719
772,0.046539,-0.497534,-0.234403,0.921374,-0.316743,0.664189,-0.046858,-0.998731,-0.415507,0.365334,...,-0.207978,-0.845558,-0.569982,-0.929915,-0.420049,-0.286877,-0.578791,0.208162,-0.728127,-0.651216
773,0.216132,1.416841,0.913485,-0.445694,-0.002810,-0.023761,0.514669,0.468997,0.009405,0.643567,...,0.459265,-0.076086,-0.381181,-0.141179,0.399946,-0.134832,0.269174,-0.494309,-0.075585,0.113162
774,0.652817,-0.484535,0.006883,-0.184007,-0.852636,-0.282260,-0.561935,0.199189,0.960025,-0.851525,...,-0.009975,-0.520795,1.295089,0.071845,-0.362991,1.138267,1.125354,1.147714,-0.075585,-0.876873
775,2.167204,-0.671451,1.376266,-0.009684,0.688786,0.475862,-0.567905,0.729152,0.406125,-0.527980,...,-0.655242,20.991139,0.784030,0.006480,0.065813,0.004994,0.967322,-0.951405,-0.649978,1.585675

### 2. Implementation of models  
MLP XGBoost LGBM Ensemble

In [30]:
from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train,y_train)

LinearRegression()

In [31]:
y_train_pred = linear_regressor.predict(X_train)

In [32]:
from sklearn.metrics import r2_score
score = r2_score(y_train, y_train_pred)
score

0.5216075785812895

In [33]:
from sklearn.preprocessing import PolynomialFeatures 
poly_reg = PolynomialFeatures(degree = 2)
X_train_poly = poly_reg.fit_transform(X_train)
poly_reg_model = LinearRegression()
poly_reg_model.fit(X_train_poly,y_train)

LinearRegression()

In [34]:
y_train_pred = poly_reg_model.predict(X_train_poly)

In [35]:
score = r2_score(y_train, y_train_pred)
score

1.0

In [44]:
poly_reg_test = PolynomialFeatures(degree = 2)
X_test_poly = poly_reg_test.fit_transform(X_test)
y_pred = poly_reg_model.predict(X_test_poly)

In [48]:
type(y_pred)

numpy.ndarray

In [61]:
y_pred

array([[ 61.02211837],
       [ 74.61609608],
       [ 66.37618233],
       [ 78.07140413],
       [ 72.61658098],
       [ 57.02407769],
       [ 67.17279624],
       [ 75.62054396],
       [ 64.00091473],
       [ 53.58395729],
       [ 77.04854939],
       [ 74.0238117 ],
       [ 65.52338248],
       [ 76.25994386],
       [ 80.00226156],
       [ 60.64326258],
       [ 85.85146262],
       [ 73.9511451 ],
       [ 61.01176484],
       [ 68.98574197],
       [ 68.20541957],
       [ 60.94295063],
       [ 98.29941503],
       [ 83.13891767],
       [ 66.97278601],
       [ 66.76813712],
       [ 54.80138486],
       [ 68.30918794],
       [ 72.42340618],
       [ 66.4319498 ],
       [ 65.0497261 ],
       [ 74.63318478],
       [ 72.71432184],
       [ 81.06416012],
       [ 59.5384188 ],
       [ 64.21255245],
       [ 55.27208681],
       [ 82.68298935],
       [ 61.89522464],
       [ 72.29005318],
       [ 64.93377186],
       [ 65.61465283],
       [ 63.98864185],
       [ 75.61838989],
       [ 33.87544613],
       [ 71.21347893],
       [ 61.48872193],
       [ 79.96389508],
       [ 80.50368527],
       [ 81.03776149],
       [ 74.18041352],
       [ 37.80496091],
       [ 66.02977792],
       [ 84.68311032],
       [ 76.6971144 ],
       [ 77.56306424],
       [ 85.39272088],
       [ 76.2672064 ],
       [ 69.92840755],
       [ 63.50678136],
       [ 79.20407942],
       [ 63.80778001],
       [ 70.55784617],
       [ 77.59334587],
       [ 79.73022278],
       [ 67.03337068],
       [ 74.4137093 ],
       [ 65.84669744],
       [ 77.33320159],
       [ 85.4097882 ],
       [ 61.16027409],
       [ 73.1574699 ],
       [ 62.92475577],
       [ 72.17479994],
       [ 66.92069405],
       [ 61.55853019],
       [ 77.31369451],
       [ 58.00384955],
       [ 74.26570072],
       [ 58.21696098],
       [ 85.05757242],
       [ 71.02061772],
       [ 68.63057771],
       [ 64.40582132],
       [ 85.9851902 ],
       [ 96.62369271],
       [ 71.69226096],
       [ 68.53195896],
       [ 65.51606409],
       [ 54.63387569],
       [ 64.3612066 ],
       [ 64.50244831],
       [ 77.54103118],
       [ 68.63855825],
       [ 76.37747184],
       [ 53.37067459],
       [ 67.66379181],
       [ 57.38275765],
       [ 60.40434038],
       [ 75.04847916],
       [ 77.48742239],
       [ 68.01920994],
       [ 65.70909145],
       [ 84.51467396],
       [ 79.21498321],
       [ 60.53508524],
       [ 64.19555733],
       [ 83.33844797],
       [ 72.1019548 ],
       [ 77.24555744],
       [ 71.87113299],
       [ 65.29949221],
       [ 65.9641334 ],
       [ 67.13900151],
       [ 57.57984076],
       [ 96.13829055],
       [ 48.11719747],
       [ 70.51524166],
       [ 67.81480112],
       [ 82.64762194],
       [ 77.43650536],
       [ 68.57710723],
       [ 64.58272883],
       [ 91.37117867],
       [ 69.8151771 ],
       [ 67.61179056],
       [ 65.20865483],
       [ 80.98542063],
       [ 81.74645798],
       [ 45.40974326],
       [ 78.45108945],
       [ 64.06069113],
       [ 80.06994353],
       [ 67.40681413],
       [ 87.11061375],
       [ 77.06770615],
       [ 59.7740853 ],
       [ 70.58718644],
       [ 70.5402155 ],
       [ 84.39458414],
       [ 72.73939683],
       [ 69.14302927],
       [ 70.62052892],
       [ 67.18886992],
       [ 63.29108183],
       [ 49.99481841],
       [ 68.55740215],
       [ 65.27912514],
       [ 67.68724345],
       [ 71.16673596],
       [ 71.47638712],
       [ 70.62488671],
       [ 68.4728325 ],
       [ 64.06345785],
       [ 65.6515412 ],
       [ 73.21035267],
       [ 69.80812857],
       [ 65.39731024],
       [ 94.67970416],
       [ 79.91107494],
       [ 85.51531176],
       [ 63.86219827],
       [ 59.85534515],
       [ 66.94012082],
       [ 73.02025681],
       [ 67.26659717],
       [ 66.65891956],
       [ 70.88611827],
       [ 68.80137488],
       [ 75.41684722],
       [ 57.89187643],
       [ 67.43651263],
       [ 62.89451388],
       [ 70.12185012],
       [ 84.74031713],
       [ 73.5282688 ],
       [ 65.72664109],
       [ 41.38709013],
       [ 90.17157346],
       [ 65.75626051],
       [ 79.42105647],
       [ 65.45098261],
       [ 66.14797034],
       [ 82.49935514],
       [ 66.75984826],
       [ 62.78036644],
       [ 68.17750371],
       [ 79.19876779],
       [ 79.4987808 ],
       [ 83.49110562],
       [ 54.91019558],
       [ 63.65611996],
       [ 74.816829  ],
       [ 56.46475028],
       [ 76.77016085],
       [ 53.90400553],
       [ 60.26945564],
       [ 81.83175075],
       [ 44.19722554],
       [ 81.82700205],
       [ 64.55254454],
       [ 69.58790478],
       [ 70.48898773],
       [ 66.89805507],
       [ 69.39795111],
       [ 83.3066222 ],
       [ 51.19886163],
       [ 79.26323229],
       [ 60.50752264],
       [ 80.83214192],
       [ 66.65979267],
       [ 64.98511273],
       [ 74.83642979],
       [ 61.54982218],
       [ 69.79222996],
       [ 58.10584466],
       [ 75.89634658],
       [ 65.09231075],
       [ 50.30910493],
       [ 77.71033855],
       [ 57.97716617],
       [ 69.9595988 ],
       [ 71.82827097],
       [ 72.1193706 ],
       [ 71.03528049],
       [ 62.35916779],
       [ 76.23889042],
       [ 80.7580585 ],
       [ 78.51838002],
       [ 59.84340096],
       [ 57.68693159],
       [ 62.830825  ],
       [ 71.33435664],
       [ 76.16490821],
       [ 82.21684292],
       [ 59.73167245],
       [ 88.5869132 ],
       [ 71.80481812],
       [ 53.74121538],
       [ 73.7682515 ],
       [ 63.94717031],
       [ 63.38640798],
       [ 69.86169337],
       [ 67.07304406],
       [ 71.90610369],
       [ 67.8398196 ],
       [ 52.94331557],
       [ 74.86839439],
       [ 74.8116553 ],
       [ 66.86213646],
       [ 70.47750851],
       [ 50.93730143],
       [ 59.9490521 ],
       [ 51.01859477],
       [ 82.87953012],
       [ 74.69117616],
       [ 56.69176136],
       [ 59.64159988],
       [ 70.35117783],
       [ 75.63558581],
       [ 71.10947344],
       [ 76.53356773],
       [ 69.95999408],
       [ 84.91504182],
       [ 60.78168753],
       [ 75.08356809],
       [ 64.10692662],
       [ 71.096631  ],
       [ 88.38549211],
       [ 57.83745642],
       [ 54.88154908],
       [ 56.53892178],
       [ 73.22072215],
       [ 61.70223247],
       [ 65.57266874],
       [ 67.38610007],
       [ 50.79716248],
       [ 77.69745994],
       [ 87.05618161],
       [ 71.95967291],
       [ 84.75147977],
       [ 71.6439255 ],
       [ 76.63720601],
       [ 76.67033126],
       [ 82.68842597],
       [ 70.59485292],
       [ 73.22707086],
       [ 78.9261135 ],
       [ 56.94261653],
       [ 68.459709  ],
       [ 72.47611025],
       [ 71.62720947],
       [ 82.41180156],
       [ 70.24729392],
       [ 77.076858  ],
       [ 69.67516543],
       [ 71.48152667],
       [ 66.71538477],
       [ 78.47352328],
       [ 70.55604427],
       [ 74.51234877],
       [ 82.85986053],
       [ 48.34709162],
       [ 63.17189265],
       [ 66.92169484],
       [ 58.29372133],
       [ 79.17161723],
       [ 69.6764236 ],
       [ 87.95564799],
       [ 72.46292792],
       [ 63.77834246],
       [ 68.82614598],
       [ 71.65717473],
       [ 66.64979148],
       [ 90.67446364],
       [ 72.09527196],
       [ 74.55700421],
       [ 86.86389469],
       [ 65.02937217],
       [ 71.47221228],
       [ 61.0769072 ],
       [ 52.61388066],
       [ 71.28012119],
       [ 60.23036001],
       [ 70.15267068],
       [ 73.91581841],
       [ 73.56529266],
       [ 75.76713652],
       [ 60.96957615],
       [ 63.39491718],
       [ 68.57407564],
       [ 66.05383027],
       [ 75.89577314],
       [ 95.37660977],
       [ 78.96684601],
       [101.88347242],
       [ 60.30239761],
       [ 57.65390453],
       [ 69.89947584],
       [ 76.60633375],
       [ 85.88325772],
       [ 84.00914255],
       [ 65.9163348 ],
       [ 83.32139975],
       [ 69.45532925],
       [ 75.75215878],
       [ 43.61516772],
       [ 65.17570957],
       [ 64.28135033],
       [ 63.52803899],
       [ 65.83194114],
       [ 70.4899495 ],
       [ 68.13371585],
       [ 72.72738685],
       [ 64.79841123],
       [ 73.13217346],
       [ 67.46133526],
       [ 65.87483302],
       [ 56.61072947],
       [ 79.89866509],
       [ 72.11530504],
       [ 69.36086883],
       [ 55.28314082],
       [ 96.49067483],
       [ 71.01940309],
       [ 77.31119501],
       [ 79.19645755],
       [ 71.20653887],
       [ 69.98374644],
       [ 57.83534876],
       [ 62.76478543],
       [ 65.36072085],
       [ 75.76140166],
       [ 80.82515611],
       [ 69.01855315],
       [ 69.33872552],
       [ 79.26368967],
       [ 69.8661546 ],
       [ 66.74980258],
       [ 81.30588838],
       [ 65.78903609],
       [ 66.74402187],
       [ 72.42396315],
       [ 68.32381542],
       [ 57.86415935],
       [ 81.68916646],
       [ 78.39423939],
       [ 70.08808788],
       [ 66.2488658 ],
       [ 72.55806674],
       [ 79.50342766],
       [ 78.43737469],
       [ 70.28082414],
       [ 67.32203836],
       [ 70.64488775],
       [ 59.17668546],
       [ 78.53105268],
       [ 59.62752712],
       [ 59.51607   ],
       [ 66.97794351],
       [ 74.75650566],
       [ 64.68168196],
       [ 63.55612209],
       [ 67.70075256],
       [ 92.0934676 ],
       [ 68.01126352],
       [ 77.42964232],
       [ 70.72390777],
       [ 53.24796903],
       [ 55.1820859 ],
       [ 75.71760959],
       [ 55.84261952],
       [ 61.26455804],
       [ 81.64759751],
       [ 11.57882203],
       [ 47.17422806],
       [ 69.06719083],
       [ 34.35444404],
       [ 76.03181294],
       [ 78.327016  ],
       [ 66.03338321],
       [ 59.1428696 ],
       [ 64.8641493 ],
       [ 62.37293002],
       [ 91.19618386],
       [ 64.90901534],
       [ 72.53022613],
       [ 67.46683866],
       [ 73.36048772],
       [ 96.08822387],
       [ 63.92412026],
       [ 71.86576839],
       [ 70.44514772],
       [ 83.17283909],
       [ 80.0754132 ],
       [ 63.97925661],
       [ 62.33732525],
       [ 82.95165279],
       [ 69.24135572],
       [ 53.25497018],
       [ 78.33989573],
       [ 69.75760926],
       [ 65.42137941],
       [ 62.01022118],
       [ 70.3227465 ],
       [ 59.05970365],
       [ 81.01953933],
       [ 61.43462547],
       [ 86.88664385],
       [ 67.92506261],
       [ 73.68466061],
       [ 78.49948213],
       [ 66.36861864],
       [ 60.36160664],
       [ 82.00462208],
       [ 71.17651015],
       [ 60.67965142],
       [ 47.98351113],
       [ 65.38091444],
       [ 61.17364309],
       [ 42.93493676],
       [ 50.45615251],
       [ 61.24309975],
       [ 72.88130173],
       [ 70.29605593],
       [ 73.33697623],
       [ 76.86404927],
       [ 74.86800853],
       [ 75.42586182],
       [ 76.22675033],
       [ 74.93419755],
       [ 66.62386179],
       [ 72.73536816],
       [ 72.11059799],
       [ 72.9399509 ],
       [ 49.60613348],
       [ 63.59499286],
       [ 77.86576699],
       [ 63.75885819],
       [ 84.99329796],
       [ 60.68048136],
       [ 64.2293833 ],
       [ 63.9273303 ],
       [ 67.62711522],
       [ 33.69339858],
       [ 88.17955439],
       [ 50.18677391],
       [ 63.8442782 ],
       [ 95.95095556],
       [ 50.69252694],
       [ 69.18003232],
       [ 68.23192182],
       [ 60.263899  ],
       [ 69.70224841],
       [ 70.59786236],
       [ 70.496438  ],
       [ 66.71232095],
       [ 80.42373913],
       [ 59.67591483],
       [ 65.0884185 ],
       [ 54.77556737],
       [ 73.51915736],
       [ 81.55259876],
       [ 53.44501503],
       [ 77.47685398],
       [ 77.16705748],
       [ 63.69586695],
       [ 74.55881202],
       [ 53.04143539],
       [ 79.87387743],
       [ 83.46423325],
       [ 90.72112835],
       [ 77.39458131],
       [ 62.65849871],
       [ 79.00451641],
       [ 64.54922885],
       [ 86.58575651],
       [ 71.47048902],
       [ 64.72018237],
       [ 57.20705034],
       [ 88.13150251],
       [ 73.063338  ],
       [ 63.57902558],
       [ 72.06383045],
       [ 78.88764375],
       [ 74.15639195],
       [ 75.37710426],
       [ 82.05593157],
       [ 64.11979787],
       [ 58.79417061],
       [ 86.4951642 ],
       [ 64.41289273],
       [ 56.0815245 ],
       [ 67.56575632],
       [ 62.56985062],
       [ 56.16881143],
       [ 70.99488586],
       [ 74.22778914],
       [ 74.23837907],
       [ 78.40815491],
       [ 68.11235315],
       [ 63.92088964],
       [ 66.86689601],
       [ 69.7202622 ],
       [ 92.89265476],
       [ 79.42937654],
       [ 70.06558893],
       [ 62.42613381],
       [ 82.03238024],
       [ 70.43233496],
       [ 72.75815929],
       [ 61.50438891],
       [ 72.63004591],
       [ 63.0897403 ],
       [ 56.06080638],
       [ 67.83434821],
       [ 78.49834412],
       [ 63.98674955],
       [ 88.1109104 ],
       [ 72.18793794],
       [ 30.25180055],
       [ 76.97492123],
       [ 77.54394689],
       [ 88.11871805],
       [ 70.74093694],
       [ 60.53127966],
       [ 71.49993657],
       [ 58.29401643],
       [ 68.8381517 ],
       [ 71.97828791],
       [ 96.80334854],
       [ 51.72286074],
       [ 77.5471545 ],
       [105.05484675],
       [ 63.44753491],
       [ 75.46180445],
       [ 74.39097868],
       [ 46.7352383 ],
       [ 86.17965158],
       [ 97.39818543],
       [ 78.29054896],
       [ 68.82907583],
       [ 69.9169172 ],
       [ 76.70793521],
       [ 54.03197149],
       [ 83.99383132],
       [ 54.66566471],
       [ 73.87110508],
       [ 79.56356518],
       [ 64.69929733],
       [ 70.07802207],
       [ 71.24884014],
       [ 59.09630656],
       [ 89.81502764],
       [ 75.09301851],
       [ 96.32599321],
       [119.85907647],
       [ 76.15316408],
       [ 62.52761444],
       [ 54.37170888],
       [ 70.75015707],
       [ 63.8302898 ],
       [ 48.42388374],
       [ 80.33989441],
       [ 63.59589086],
       [ 69.74709231],
       [ 63.35278331],
       [ 64.53272387],
       [ 62.67499842],
       [ 72.03579337],
       [ 74.5381553 ],
       [ 54.13517314],
       [ 76.26267274],
       [ 52.41339811],
       [ 65.01631705],
       [ 68.90350514],
       [ 82.25529025],
       [ 54.95803553],
       [ 69.90688378],
       [ 84.00759639],
       [ 78.1055077 ],
       [ 51.65367152],
       [ 64.35536168],
       [ 67.44745173],
       [ 87.82854532],
       [ 67.31551221],
       [ 75.51198919],
       [ 75.5207502 ],
       [ 58.47808768],
       [ 54.64120549],
       [ 97.7586848 ],
       [ 68.45120648],
       [ 86.09295985],
       [ 65.83751476],
       [ 60.75000506],
       [ 87.98767128],
       [ 72.6832306 ],
       [ 85.10106241],
       [ 92.63086133],
       [ 69.12166091],
       [ 67.70797414],
       [ 61.46426821],
       [ 68.79038078],
       [ 70.9862442 ],
       [ 75.94661519],
       [ 67.79856128],
       [ 73.46993018],
       [ 72.12876935],
       [ 59.80961391],
       [ 78.21605741],
       [ 68.8563299 ],
       [ 67.52209517],
       [ 50.89324369],
       [ 70.69176049],
       [ 67.44308211],
       [ 67.86085444],
       [ 86.39425964],
       [ 67.01153379],
       [ 54.83419652],
       [ 63.49949925],
       [ 63.81854974],
       [ 57.93969789],
       [ 73.58353653],
       [ 69.33448743],
       [ 73.5207958 ],
       [ 63.2781011 ],
       [ 59.05129682],
       [ 86.49116777],
       [ 50.72380132],
       [ 54.51251516],
       [ 74.68758312],
       [ 79.62088008],
       [ 54.71962148],
       [ 58.34517828],
       [ 76.87209546],
       [ 65.719334  ],
       [ 71.4908154 ],
       [ 70.37316959],
       [ 63.82295683],
       [ 74.5571593 ],
       [ 79.27033089],
       [ 77.94315987],
       [ 75.71083533],
       [ 77.66301934],
       [ 72.46146182],
       [ 69.24524728],
       [ 70.66957655],
       [ 76.32529507],
       [ 81.34321956],
       [ 67.98736908],
       [135.99125325],
       [ 73.79394338],
       [ 55.37980308],
       [ 54.83184532],
       [ 61.04838915],
       [ 66.66881359],
       [ 81.90953495],
       [ 43.39497614],
       [ 76.90733367],
       [ 69.55338722],
       [ 59.95086822],
       [ 71.29020043],
       [ 66.63146267],
       [ 68.12710643],
       [ 52.72356617],
       [ 62.05976377],
       [ 75.14581784],
       [ 66.95077758],
       [ 73.05368312],
       [ 82.19236873],
       [ 73.77454927],
       [ 96.32451982],
       [ 70.53634923],
       [ 59.65440774],
       [ 85.2222744 ],
       [ 72.64225603],
       [ 75.2357481 ],
       [ 63.02892566],
       [ 68.98790277],
       [ 60.89625221],
       [ 66.50164613],
       [ 73.60384055],
       [ 64.51907559],
       [ 43.05419459],
       [ 59.35813002],
       [ 81.48238354],
       [ 75.89949855],
       [ 72.47600386],
       [ 61.98696949],
       [ 67.73335441],
       [ 60.67479048],
       [ 76.28606221],
       [ 65.51930557],
       [ 92.27268264],
       [ 67.51470524],
       [ 63.32351319],
       [ 72.76361015],
       [ 64.48877175],
       [ 67.16553502],
       [ 47.50897722],
       [ 60.9867075 ],
       [ 77.71626068],
       [ 66.0330144 ],
       [ 68.77096022],
       [ 72.28935609],
       [ 82.29735402],
       [ 73.83103267],
       [ 88.59860866],
       [ 71.79027205],
       [ 73.67494045],
       [ 64.06649195],
       [ 50.57331209],
       [ 57.67957157],
       [ 62.98760668],
       [ 69.37079457],
       [ 67.99905547],
       [ 62.30560454],
       [ 67.45838459],
       [ 71.48936751],
       [ 69.75401555],
       [ 62.96443476],
       [ 62.97547386],
       [ 56.48376638],
       [ 62.70944441],
       [ 75.50122888],
       [ 82.49540725],
       [ 68.51695309],
       [ 64.02641514],
       [ 41.29460349],
       [ 62.65948413],
       [ 79.35949573],
       [ 68.24274943],
       [ 75.55179728],
       [ 77.86063137],
       [ 76.72709817],
       [ 84.8298968 ]])

In [47]:
X_test.shape

(776, 80)

In [59]:
result =  pd.DataFrame({'id': np.arange(len(y_pred)), 'y': y_pred.reshape(-1)})
result

      id          y
0      0  61.022118
1      1  74.616096
2      2  66.376182
3      3  78.071404
4      4  72.616581
..   ...        ...
771  771  68.242749
772  772  75.551797
773  773  77.860631
774  774  76.727098
775  775  84.829897

[776 rows x 2 columns]

In [60]:
result.to_csv("Result_LogisticRegression.csv",index=False)

#### Model 1 Regression Ridge

In [36]:
from sklearn.linear_model import Ridge,RidgeCV

#### Model 2 Regression Lasso

#### Model 3 ElasticNet

#### Model 4 Random Forest

#### Model 5 XGBoost

In [37]:
import xgboost
print(xgboost.__version__)

1.5.0

C:\Users\zheng\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [38]:
from xgboost import XGBRegressor

In [39]:
from sklearn.model_selection import cross_val_score

In [40]:
scores = cross_val_score(XGBRegressor(), X, y, scoring='neg_mean_squared_error')

NameError: name 'X' is not defined